server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/security?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: cos
    password: cos1234

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache

  jpa:
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    #          ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDB53Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(LjW/KNmZg24phck4W3+ZUk2FGzi/QxNTmYL2/g0C8P46qImhSbx+1cq4ueAX9MVNjTt3njjuqWiLQvgWV0CH/dM0RDI/VycQjnJ8uJDwOsHR/9eli2p7Ww==)
            client-secret: ENC(4xdWYyAsZGtzD0WbdCQi8PjLTNffiS3vLFyF8fqL36z9Su/rbhCCkwo+Sj184TqO)
            scope:
              - email
              - profile
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
